export enum ESceneReduxActions {
  SET_ASPECT_RATIO = 'SCENE/SET_ASPECT_RATIO',
  SET_IMAGE_LOADED = 'SCENE/SET_IMAGE_LOADED',
  SET_IS_MAIN_CONTENT_SCROLL_TRIGGER = 'SCENE/SET_IS_MAIN_CONTENT_SCROLL_TRIGGER',
}
