export enum Element {
  LOGO = 'logo',
  FLAMES = 'flames',
  SPARKLES = 'sparkles',
  EYE = 'eye',
  TERRAIN = 'terrain',
  EYE_FLAMES_SPACER = 'eyeFlamesSpacer',
  CONTENT_FADER = 'contentFader',
  MAIN = 'main',
  MENU_BUTTON = 'menuButton',
  MENU_CLOSE = 'menuClose',
  MENU_ICON_OUTLINE = 'menuIconOutline',
  MENU_ICON_FADER = 'menuIconFader',
  MENU_ICON_TEXT = 'menuIconText',
  MENU_LIST_IMAGE = 'menuListImage',
  FOOTER_COPYRIGHT = 'footerCopyright',
  FOOTER_DEVELOPED_BY = 'footerDevelopedBy',
  SCROLL_INDICATOR = 'scrollIndicator',
}

export enum EImage {
  LOGO = 'LOGO',
  EIGHT_ICON = 'EIGHT_ICON',
  FLAMES_BASE = 'FLAMES_BASE',
  FLAMES_CLONE = 'FLAMES_CLONE',
  FLAMES_LIGHT = 'FLAMES_LIGHT',
  FLAMES_NEUTRAL = 'FLAMES_NEUTRAL',
  FLAMES_DARK = 'FLAMES_DARK',
  SPARKLES_BASE = 'SPARKLES_BASE',
  SPARKLES_1 = 'SPARKLES_1',
  SPARKLES_2 = 'SPARKLES_2',
  SPARKLES_3 = 'SPARKLES_3',
  SPARKLES_4 = 'SPARKLES_4',
  TERRAIN = 'TERRAIN',
}
